version: '3.8'
services:
  db:
    image: postgres:16.1
    container_name: document-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: document
      POSTGRES_USER: document
      POSTGRES_DB: document-db