server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/document-db
    username: document
    password: document
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

worker:
  submit:
    enabled: true
    fixed-delay: 60000 # 1 minute
    batch-size: 100
  approve:
    enabled: true
    fixed-delay: 60000 # 1 minute
    batch-size: 100

logging:
  level:
    com.itqgroup: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"